"""Text cleaning, normalization, language detection, and section parsing.

These helpers are source-agnostic. Adapters hand raw markdown/text to the
pipeline, which uses the functions here to produce indexable chunks.
"""

import html
import re
import unicodedata

ATX_RE = re.compile(r"^#{1,6}\s+(.+?)(?:\s*#*\s*)?$")

# Arabic (and Persian) combining marks to strip before indexing.
_ARABIC_DIACRITICS = re.compile(r"[\u064b-\u065f\u0670]")


def normalize_persian(text):
    """Normalize Arabic/Persian variants so ك/ک and ي/ی match each other."""
    text = text.replace("\u0640", "")  # tatweel
    text = _ARABIC_DIACRITICS.sub("", text)
    text = text.replace("\u0643", "\u06a9")  # arabic kaf -> persian kaf
    text = text.replace("\u06aa", "\u06a9")  # swash kaf -> persian kaf
    text = text.replace("\u064a", "\u06cc")  # arabic yeh -> persian yeh
    text = text.replace("\u0649", "\u06cc")  # alef maksura -> persian yeh
    return text


def normalize_text(text):
    """Full normalization applied to both indexed text and queries."""
    return normalize_persian(unicodedata.normalize("NFKC", text))


def slugify(value):
    """Unicode slugify, matching the heading ids generated by blog/build.py."""
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"[\s]+", "-", value)


def detect_lang(text):
    """Very small script-based language detector (Persian/Arabic vs Latin)."""
    arabic = sum(1 for c in text if "\u0600" <= c <= "\u06ff")
    latin = sum(1 for c in text if "a" <= c.lower() <= "z")
    return "fa" if arabic > latin else "en"


def strip_markdown(text):
    """Reduce markdown (and LaTeX/math) to plain text suitable for indexing."""
    t = text
    # Fenced code blocks: keep the code, drop the fence
    t = re.sub(r"```[^\n]*\n(.*?)```", r"\1", t, flags=re.DOTALL)
    t = re.sub(r"~~~[^\n]*\n(.*?)~~~", r"\1", t, flags=re.DOTALL)
    # Inline code
    t = re.sub(r"`([^`]*)`", r"\1", t)
    # Images -> alt text, links -> link text
    t = re.sub(r"!\[([^\]]*)\]\([^)]*\)", r"\1", t)
    t = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", t)
    t = re.sub(r"\[([^\]]+)\]\[[^\]]*\]", r"\1", t)
    # Link definitions and footnote references
    t = re.sub(r"(?m)^\s*\[[^\]]+\]:\s*\S+.*$", "", t)
    t = re.sub(r"\[\^[^\]]*\]", "", t)
    # Raw HTML
    t = re.sub(r"<[^>]+>", " ", t)
    # LaTeX: display, inline, \(...\), then commands
    t = re.sub(r"\$\$(.+?)\$\$", r" \1 ", t, flags=re.DOTALL)
    t = re.sub(r"\\\[(.*?)\\\]", r" \1 ", t, flags=re.DOTALL)
    t = re.sub(r"\$([^$\n]+?)\$", r" \1 ", t)
    t = re.sub(r"\\\((.*?)\\\)", r" \1 ", t, flags=re.DOTALL)
    t = re.sub(r"\\([a-zA-Z]+)", r"\1", t)
    t = t.replace("{", " ").replace("}", " ").replace("\\", " ")
    # Emphasis and other markdown punctuation
    t = re.sub(r"[*_~>#]", " ", t)
    # Setext underlines and horizontal rules
    t = re.sub(r"(?m)^\s*[-=]{2,}\s*$", "", t)
    t = html.unescape(t)
    # Whitespace cleanup
    t = re.sub(r"[ \t\f\v]+", " ", t)
    t = re.sub(r"\n{3,}", "\n\n", t)
    t = "\n".join(line.strip() for line in t.splitlines())
    return t.strip()


def sectionize(markdown_text):
    """Split markdown into (heading, anchor, body) sections at ATX headings.

    Heading text is stripped from the body and carried separately so chunks can
    cite the section they came from and link to its anchor.
    """
    sections = []
    heading = ""
    anchor = ""
    buf = []

    for line in markdown_text.splitlines():
        match = ATX_RE.match(line.strip())
        if match:
            if buf:
                sections.append((heading, anchor, "\n".join(buf)))
                buf = []
            heading = re.sub(r"\*\*(.+?)\*\*", r"\1", match.group(1).strip())
            anchor_match = re.search(r"\{#([^}]*)\}\s*$", heading)
            if anchor_match:
                anchor = anchor_match.group(1)
                heading = re.sub(r"\s*\{#[^}]*\}\s*$", "", heading).strip()
            else:
                anchor = slugify(heading)
        else:
            buf.append(line)

    if buf:
        sections.append((heading, anchor, "\n".join(buf)))
    return sections


def split_long(text, max_chars):
    """Split text into <= max_chars pieces, preferring paragraph boundaries."""
    if len(text) <= max_chars:
        return [text]

    pieces = []
    current = ""
    for paragraph in text.split("\n\n"):
        paragraph = paragraph.strip()
        if not paragraph:
            continue
        if len(paragraph) > max_chars:
            if current:
                pieces.append(current)
                current = ""
            line = ""
            for word in paragraph.split():
                if len(line) + len(word) + 1 > max_chars:
                    if line:
                        pieces.append(line)
                    line = word
                else:
                    line = (line + " " + word).strip()
            if line:
                current = line
        elif current and len(current) + len(paragraph) + 2 > max_chars:
            pieces.append(current)
            current = paragraph
        else:
            current = (current + "\n\n" + paragraph) if current else paragraph
    if current:
        pieces.append(current)
    return pieces
